### ISSUE TITLE
Regarding the reference to ‘Comparison with Baseline Methods’ in the paper.

### ISSUE THREAD

**Issue by syf997819611** [Rex-sys-hk/PlanScope#1]
Excuse me. May I ask you a question? Why is the score of baseline(pluto) different from the score given in its paper?

**Comment by Rex-sys-hk** [comment]
To reduce the impact of artificially constructed negative samples, we disabled the CIL module in PLUTO for comparison, as we have claimed in our paper.

**Comment by Rex-sys-hk** [comment]
In addition, perhaps we need to state that we are not SOTA as described by an unauthorized public account. There are several models that perform better on the nuPlan planning task. Our article only discusses a possible way to improve the performance of the planning model.

**Comment by syf997819611** [comment]
Thank you for your answer, it helped me a lot.
