### ISSUE TITLE
Question about Visualization like your paper

### ISSUE THREAD

**Issue by Yyb-XJTU** [Rex-sys-hk/PlanScope#4]
![image](https://github.com/user-attachments/assets/db62ae2d-fd0c-49eb-98cd-1c8cccef5974)
What an excellent work! How can I visualize the results shown in your paper?

**Comment by Rex-sys-hk** [comment]
It can be rendered with the flag <planner.$PLANNER.render=true> as shown in sim_pluto.sh.

**Comment by Yyb-XJTU** [comment]
Thank you, I'll try it.
